path: 'C:/Users/Vu Diep/Desktop/Machine-Learning/YOLO'
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')
nc: 2
names: ['player', 'football']